Repository HiltonThallyson/GC-bank-project, pull requests merged in 2023-05, with the labels that each got.

#2 Criando arquitetura básica do projeto
  .gitignore
  README.md
  src/back/Banco.java
  src/back/BancoServices.java
  src/back/Conta.java
  src/front/Main.java
  src/module-info.java
Labels: feature

#4 Funcionalidade de cadastro de conta adicionada
  src/back/BancoServices.java
  src/front/Main.java
Labels: feature

#11 Funcionalidade de creditar valor em conta criado
  src/back/BancoServices.java
  src/front/Main.java
Labels: feature

#13 funcionalidade debitar de conta adicionada
  src/back/BancoServices.java
  src/front/Main.java
Labels: feature

#12 Adicionando a funcionalidade de consultar o saldo
  src/back/BancoServices.java
  src/front/Main.java
Labels: feature

#14 adicionada funcionalidade de transferir PR
  src/back/BancoServices.java
  src/front/Main.java
Labels: feature

#21 19 cadastrar conta poupanca
  src/back/BancoServices.java
  src/back/Conta.java
  src/back/ContaPoupanca.java
  src/front/Main.java
Labels: feature

#20 Criando a feature de conta bonus
  src/back/BancoServices.java
  src/back/Conta.java
  src/back/ContaBonus.java
  src/back/TipoDeTransacao.java
  src/front/Main.java
Labels: feature

#29 Saldo inicial na criação de conta poupança
  src/back/BancoServices.java
  src/back/Conta.java
  src/back/ContaPoupanca.java
  src/front/Main.java
Labels: feature

#31 Adiciona a possibilidade de saldo negativo de ate 1000 em contas simples e poupança
  src/back/BancoServices.java
  src/back/Conta.java
  src/back/ContaPoupanca.java
  src/front/Main.java
Labels: feature

#35 fix-alterando regra de pontuação
  src/back/ContaBonus.java
Labels: homologation

#36 Update README.md
  README.md
Labels: documentation
